# Generated by Django 5.0.6 on 2025-02-05 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.TimeField(verbose_name='Время сеанса')),
                ('hall_number', models.IntegerField(verbose_name='Номер зала')),
                ('seat_number', models.IntegerField(verbose_name='Номер места')),
                ('price', models.IntegerField(verbose_name='Стоимость билета')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR код')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.film', verbose_name='Фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
