# Generated by Django 5.0.6 on 2025-02-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_hall'),
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film_app.hall', verbose_name='Зал'),
        ),
    ]
