# Generated by Django 5.0.6 on 2025-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0002_alter_ticket_hall'),
        ('reservation', '0002_hall_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
