# Generated by Django 5.0.6 on 2025-02-01 13:33

import django.db.models.deletion
import film_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Режиссёр', 'Режиссёр'), ('Актёр', 'Актёр'), ('Продюсер', 'Продюсер'), ('Режиссер дубляжа', 'Режиссер дубляжа'), ('Переводчик', 'Переводчик'), ('Актер дубляжа', 'Актер дубляжа'), ('Сценарист', 'Сценарист'), ('Оператор', 'Оператор'), ('Композитор', 'Композитор'), ('Художник', 'Художник'), ('Монтажер', 'Монтажер')], max_length=50, verbose_name='Статус')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='people_photo/%Y/%m/%d/', validators=[film_app.validators.photo_actor_resolution_validator], verbose_name='Фото')),
                ('biography', models.TextField(verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название фильма')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='film_photo/%Y/%m/%d/', validators=[film_app.validators.photo_resolution_validator], verbose_name='Постер')),
                ('video', models.FileField(blank=True, upload_to='film_video/%Y/%m/%d/', verbose_name='Трейлер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(validators=[film_app.validators.year_of_film_release_validator], verbose_name='Год выпуска')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.category', verbose_name='Категория')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.people', verbose_name='Актёры')),
            ],
        ),
    ]
