# Generated by Django 5.0.6 on 2025-02-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='film_app.film', verbose_name='Фильм'),
            preserve_default=False,
        ),
    ]
