# Generated by Django 5.0.6 on 2025-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='grade',
            field=models.IntegerField(blank=True, default=1, verbose_name='Оценка'),
        ),
    ]
