# Generated by Django 5.0.6 on 2025-02-22 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_film_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='grade',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
