# Generated by Django 5.0.6 on 2025-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_remove_film_actor_people_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(verbose_name='Количество посадочных мест в одном ряду')),
                ('rows', models.IntegerField(verbose_name='Количество рядов')),
            ],
        ),
    ]
