# Generated by Django 5.0.6 on 2025-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_sessions_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
