# Generated by Django 5.0.6 on 2025-02-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='film_app.sessions', verbose_name='Зал'),
            preserve_default=False,
        ),
    ]
