# Generated by Django 5.0.6 on 2025-02-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0004_hall_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='session',
        ),
        migrations.AddField(
            model_name='hall',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='film_app.film', verbose_name='Фильм'),
            preserve_default=False,
        ),
    ]
