# Generated by Django 5.0.6 on 2025-02-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0004_alter_sessions_film'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
    ]
